import * as THREE from './vendor/three.module.js';

// 与已确认的独立天竺葵模型共用同一套几何、材质和随机种子。
export function createGeranium(renderer){
  const model=new THREE.Group();
  model.name='Geranium_Model';

  const potMat=new THREE.MeshPhysicalMaterial({color:0xa54e32,roughness:.67,metalness:0,clearcoat:.08,clearcoatRoughness:.8});
  const rimMat=new THREE.MeshPhysicalMaterial({color:0x9b422c,roughness:.7,clearcoat:.05});
  const soilMat=new THREE.MeshStandardMaterial({color:0x241710,roughness:1});
  const potProfile=[new THREE.Vector2(.068,0),new THREE.Vector2(.073,.012),new THREE.Vector2(.078,.03),new THREE.Vector2(.092,.145),new THREE.Vector2(.1,.16),new THREE.Vector2(.1,.174),new THREE.Vector2(.092,.18),new THREE.Vector2(.086,.166),new THREE.Vector2(.073,.02)];
  const pot=new THREE.Mesh(new THREE.LatheGeometry(potProfile,72),potMat);pot.name='Pot';pot.castShadow=pot.receiveShadow=true;model.add(pot);
  const potRim=new THREE.Mesh(new THREE.TorusGeometry(.096,.008,12,72),rimMat);potRim.rotation.x=Math.PI/2;potRim.position.y=.169;potRim.castShadow=true;model.add(potRim);
  const soil=new THREE.Mesh(new THREE.CylinderGeometry(.087,.087,.008,64),soilMat);soil.position.y=.169;soil.receiveShadow=true;model.add(soil);
  for(let i=0;i<6;i++){const foot=new THREE.Mesh(new THREE.BoxGeometry(.025,.01,.018),rimMat);const a=i/6*Math.PI*2;foot.position.set(Math.cos(a)*.06,.006,Math.sin(a)*.06);foot.rotation.y=-a;model.add(foot)}

  function leafTexture(seed=0){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d');x.clearRect(0,0,512,512);const g=x.createRadialGradient(256,275,25,256,256,245);g.addColorStop(0,seed%2?'#71994a':'#668f42');g.addColorStop(.45,seed%3?'#4f7e37':'#58883b');g.addColorStop(.68,'#385f2e');g.addColorStop(.82,'#4c7736');g.addColorStop(1,'#315927');x.fillStyle=g;x.fillRect(0,0,512,512);x.globalAlpha=.3;x.strokeStyle='#243f24';x.lineWidth=34;x.beginPath();x.arc(256,268,155,0,Math.PI*2);x.stroke();x.globalAlpha=.78;x.strokeStyle='#b0c478';x.lineWidth=4;for(let i=0;i<11;i++){const a=-Math.PI*.94+i*Math.PI*1.88/10;x.beginPath();x.moveTo(256,285);x.quadraticCurveTo(256+Math.cos(a)*70,285+Math.sin(a)*70,256+Math.cos(a)*225,285+Math.sin(a)*225);x.stroke()}x.globalAlpha=.35;x.strokeStyle='#dae1ad';x.lineWidth=1;for(let i=0;i<11;i++){const a=-Math.PI*.94+i*Math.PI*1.88/10;for(let j=1;j<5;j++){const r=42+j*32,px=256+Math.cos(a)*r,py=285+Math.sin(a)*r;x.beginPath();x.moveTo(px,py);x.lineTo(px+Math.cos(a+.8)*28,py+Math.sin(a+.8)*28);x.moveTo(px,py);x.lineTo(px+Math.cos(a-.8)*28,py+Math.sin(a-.8)*28);x.stroke()}}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=renderer.capabilities.getMaxAnisotropy();return t}
  const leafMaps=[leafTexture(0),leafTexture(1),leafTexture(2),leafTexture(3)];
  const leafMaterials=leafMaps.map((map,i)=>new THREE.MeshPhysicalMaterial({map,color:[0xd7efd0,0xc8e5c2,0xbddcaf,0xd8eabd][i],roughness:.73,metalness:0,sheen:.36,sheenColor:new THREE.Color(0x96c877),side:THREE.DoubleSide,alphaTest:.05}));
  const undersideMat=new THREE.MeshPhysicalMaterial({color:0x7e9d68,roughness:.82,sheen:.18,side:THREE.BackSide});
  const stemMat=new THREE.MeshPhysicalMaterial({color:0x5d8d42,roughness:.72,metalness:0});
  function leafShape(){const shape=new THREE.Shape();const pts=[];const n=72;for(let i=0;i<n;i++){const a=i/n*Math.PI*2;let r=.5*(1+.075*Math.cos(9*a)+.028*Math.cos(18*a));const top=Math.sin(a);if(top<-.72)r*=.82;pts.push(new THREE.Vector2(Math.cos(a)*r,Math.sin(a)*r*.9+.05))}shape.moveTo(pts[0].x,pts[0].y);for(let i=1;i<pts.length;i++)shape.lineTo(pts[i].x,pts[i].y);shape.closePath();return shape}
  const leafGeometry=new THREE.ExtrudeGeometry(leafShape(),{depth:.014,bevelEnabled:true,bevelSegments:2,bevelSize:.008,bevelThickness:.005,curveSegments:2});leafGeometry.center();
  const leafPositions=leafGeometry.attributes.position;
  for(let i=0;i<leafPositions.count;i++){const x=leafPositions.getX(i),y=leafPositions.getY(i),radial=Math.min(1,Math.hypot(x,y)/.5),centerArch=.075*(1-radial*radial),edgeDroop=.022*Math.pow(radial,2.4);leafPositions.setZ(i,leafPositions.getZ(i)+centerArch-edgeDroop)}
  leafPositions.needsUpdate=true;leafGeometry.computeVertexNormals();
  function stemTo(end,thickness=.006,colorMat=stemMat,start=new THREE.Vector3(0,.168,0)){const mid=start.clone().lerp(end,.54);mid.x*=.62;mid.z*=.62;mid.y+=.035;const curve=new THREE.CatmullRomCurve3([start,mid,end]);const stem=new THREE.Mesh(new THREE.TubeGeometry(curve,12,thickness,7,false),colorMat);stem.castShadow=true;model.add(stem);return stem}
  function makeLeaf({pos,size,azimuth,tilt=.05,roll=0,map=0,selected=false}){const holder=new THREE.Group();holder.name=selected?'ExperimentLeaf':'Leaf';holder.position.copy(pos);holder.rotation.set(tilt,azimuth,roll);const mat=leafMaterials[map%leafMaterials.length].clone();if(selected){mat.emissive.set(0x6b5914);mat.emissiveIntensity=.18}const mesh=new THREE.Mesh(leafGeometry,[mat,mat]);mesh.name='LeafBlade';mesh.scale.set(size*1.12,size,size*.7);mesh.rotation.x=-Math.PI/2;mesh.castShadow=mesh.receiveShadow=true;holder.add(mesh);const back=new THREE.Mesh(leafGeometry,undersideMat);back.scale.copy(mesh.scale);back.rotation.copy(mesh.rotation);back.position.y=-.001;holder.add(back);model.add(holder);return holder}

  const leaves=[];let experimentLeaf=null;
  const rings=[{count:12,rMin:.15,rMax:.255,y:.29,size:.18},{count:14,rMin:.11,rMax:.225,y:.405,size:.155},{count:8,rMin:.07,rMax:.165,y:.53,size:.12}];
  let seed=13;function rnd(){seed=(seed*16807)%2147483647;return(seed-1)/2147483646}
  for(let ringIndex=0;ringIndex<rings.length;ringIndex++){const cfg=rings[ringIndex];for(let i=0;i<cfg.count;i++){const a=i/cfg.count*Math.PI*2+(ringIndex*.31)+(rnd()-.5)*.22,r=THREE.MathUtils.lerp(cfg.rMin,cfg.rMax,rnd()),isSelected=ringIndex===0&&i===4;const pos=isSelected?new THREE.Vector3(-.225,.335,.17):new THREE.Vector3(Math.cos(a)*r,cfg.y+(rnd()-.5)*.075,Math.sin(a)*r);const size=cfg.size*(.82+rnd()*.28),tiltSpread=[.76,.56,.42][ringIndex],rollSpread=[.42,.32,.24][ringIndex],tilt=ringIndex===2?.34+rnd()*.45:(rnd()-.5)*tiltSpread,roll=(rnd()-.5)*rollSpread,start=new THREE.Vector3((rnd()-.5)*.035,.17,(rnd()-.5)*.035);stemTo(pos.clone().add(new THREE.Vector3(0,-.015,0)),.0045+rnd()*.0018,stemMat,start);const leaf=makeLeaf({pos,size,azimuth:-a+Math.PI/2,tilt,roll,map:i+ringIndex,selected:isSelected});if(isSelected){leaf.rotation.set(THREE.MathUtils.degToRad(28),THREE.MathUtils.degToRad(-35),THREE.MathUtils.degToRad(-3));experimentLeaf=leaf;experimentLeaf.userData.home={position:leaf.position.clone(),rotation:leaf.rotation.clone(),scale:leaf.scale.clone()};experimentLeaf.userData.detachedScale=1;experimentLeaf.userData.cupScale=.6}leaves.push(leaf)}}
  function flowerPetal(color){const m=new THREE.Mesh(new THREE.SphereGeometry(.019,14,9),new THREE.MeshPhysicalMaterial({color,roughness:.54,sheen:.58,sheenColor:new THREE.Color(0xff9b80),emissive:new THREE.Color(color).multiplyScalar(.07)}));m.scale.set(1.25,.24,.88);m.castShadow=true;return m}
  function flowerCluster(center,scale=1){const cluster=new THREE.Group();cluster.position.copy(center);cluster.rotation.x=-Math.PI*.46;const colors=[0xf1432d,0xff563b,0xd92e24,0xf76546];for(let i=0;i<17;i++){const a=i*.91,r=.012+.055*Math.sqrt(i/17),y=(rnd()-.5)*.035,flower=new THREE.Group();flower.position.set(Math.cos(a)*r,y,Math.sin(a)*r*.75);flower.rotation.set((rnd()-.5)*.28,rnd()*Math.PI*2,(rnd()-.5)*.25);for(let p=0;p<5;p++){const petal=flowerPetal(colors[(i+p)%colors.length]),pa=p/5*Math.PI*2;petal.position.set(Math.cos(pa)*.018,0,Math.sin(pa)*.018);petal.rotation.y=-pa;flower.add(petal)}flower.add(new THREE.Mesh(new THREE.SphereGeometry(.009,10,6),new THREE.MeshStandardMaterial({color:0x5b3718,roughness:.9})));cluster.add(flower)}cluster.scale.setScalar(scale);model.add(cluster);return cluster}
  const flowerStemMat=new THREE.MeshPhysicalMaterial({color:0x527d38,roughness:.78});
  const flowerTop=new THREE.Vector3(.075,.69,.015);stemTo(flowerTop,.006,flowerStemMat,new THREE.Vector3(.018,.17,.005));flowerCluster(flowerTop,.78);
  const flowerTop2=new THREE.Vector3(-.105,.61,-.055);stemTo(flowerTop2,.005,flowerStemMat,new THREE.Vector3(-.018,.17,-.01));flowerCluster(flowerTop2,.50);
  const budStemEnd=new THREE.Vector3(.19,.625,-.02);stemTo(budStemEnd,.0048,flowerStemMat,new THREE.Vector3(.025,.17,0));const budGroup=new THREE.Group();budGroup.position.copy(budStemEnd);for(let i=0;i<7;i++){const b=new THREE.Mesh(new THREE.SphereGeometry(.013,10,7),new THREE.MeshStandardMaterial({color:i<2?0xb83322:0x668c40,roughness:.75})),a=i/7*Math.PI*2;b.position.set(Math.cos(a)*.027,(i%2)*.012,Math.sin(a)*.027);b.scale.y=1.4;b.castShadow=true;budGroup.add(b)}model.add(budGroup);
  const selectionRing=new THREE.Mesh(new THREE.TorusGeometry(.118,.004,8,72),new THREE.MeshBasicMaterial({color:0xffe478,transparent:true,opacity:.85}));selectionRing.rotation.x=Math.PI/2;selectionRing.position.y=.018;experimentLeaf.add(selectionRing);
  return {group:model,experimentLeaf,selectionRing,leaves};
}
