import * as THREE from './vendor/three.module.js';
import {createGeranium} from './geranium-factory.js';
import {createPaperCoverModels} from './paper-cover-factory.js';
import {setupLeafTransfer} from './leaf-transfer.js';
import {setupLeafRinse} from './leaf-rinse.js';
import {setupLeafStain} from './leaf-stain.js';
import {setupPhenomenonCloseup} from './phenomenon-closeup.js';
import {setupSceneNavigation} from './scene-navigation.js';
import {setupWaterBath} from './water-bath.js?v=lit-drag-3';
import {createLargeBeaker,createSmallBeaker,createPetriDish,createTripod,createWireGauze,createAlcoholLamp,createWashBottle,createAlcoholBottle,createIodineBottle,createTweezers,createMatchbox} from './approved-equipment-factory.js';

const W=1672,H=941,stage=document.querySelector('#stage'),mount=document.querySelector('#webgl');
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(W,H,false);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;mount.append(renderer.domElement);
const scene=new THREE.Scene();
const camera=new THREE.OrthographicCamera(-8.36,8.36,4.705,-4.705,.1,40);camera.position.set(0,8.7,12.8);camera.lookAt(0,.55,0);
scene.add(new THREE.HemisphereLight(0xe6f5ef,0x24302c,2));const key=new THREE.DirectionalLight(0xffe4bb,4.3);key.position.set(-5,9,7);key.castShadow=true;key.shadow.mapSize.set(2048,2048);scene.add(key);const sun=new THREE.DirectionalLight(0xffcf82,2.4);sun.position.set(8,6,5);scene.add(sun);

const roots=[],pickables=[],homes=new Map();let experimentMode=false,drag=null,paused=false,darkTimer=null,darkSeconds=10,darkComplete=false,lightTimer=null,lightElapsed=0,lightComplete=false,step='dark';
const glass=new THREE.MeshPhysicalMaterial({color:0xe7fbff,roughness:.08,transmission:.83,transparent:true,opacity:.42,ior:1.46,thickness:.08,side:THREE.DoubleSide,depthWrite:false});
const glassEdge=new THREE.MeshPhysicalMaterial({color:0xd8f6f2,roughness:.12,transmission:.55,transparent:true,opacity:.72,side:THREE.DoubleSide});
const metal=new THREE.MeshStandardMaterial({color:0xb8c2bf,roughness:.28,metalness:.78});
const darkMetal=new THREE.MeshStandardMaterial({color:0x202827,roughness:.52,metalness:.68});
const black=new THREE.MeshStandardMaterial({color:0x111616,roughness:.92});
function add(parent,obj,pos){obj.position.set(...pos);parent.add(obj);return obj}function box(w,h,d,mat,p=[0,0,0]){return add(new THREE.Group(),new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat),p)}
function root(name,label,pos,scale=1){const g=new THREE.Group();g.name=name;g.userData={label,draggable:true};g.position.set(pos[0],pos[1]-1.58,pos[2]);g.scale.setScalar(scale*1.28);scene.add(g);roots.push(g);homes.set(g,{position:g.position.clone(),rotation:g.rotation.clone(),scale:g.scale.clone()});return g}
function finish(g,hit){hit.userData.root=g;hit.material=new THREE.MeshBasicMaterial({transparent:true,opacity:.001,depthWrite:false});g.add(hit);pickables.push(hit);g.traverse(o=>{if(o.isMesh&&o!==hit){o.castShadow=true;o.receiveShadow=true}});return g}
function mountApprovedGeranium(){const asset=createGeranium(renderer),g=asset.group;g.name='plant';asset.selectionRing.visible=false;g.userData={label:'天竺葵（实验植物）',draggable:true,experimentLeaf:asset.experimentLeaf,selectionRing:asset.selectionRing};g.position.set(5.05,-1.58,-.35);g.scale.setScalar(3.15);scene.add(g);roots.push(g);homes.set(g,{position:g.position.clone(),rotation:g.rotation.clone(),scale:g.scale.clone()});const hit=new THREE.Mesh(new THREE.CylinderGeometry(.36,.31,.78,24));hit.position.y=.39;finish(g,hit);return g}
function registerApprovedRoot(g,name,label,pos,scale,hit){g.name=name;g.userData={...g.userData,label,draggable:true};g.position.set(pos[0],pos[1]-1.58,pos[2]);g.scale.setScalar(scale);scene.add(g);roots.push(g);homes.set(g,{position:g.position.clone(),rotation:g.rotation.clone(),scale:g.scale.clone()});return finish(g,hit)}
function mountApprovedEquipment(asset,name,label,pos,scale=1){asset.group.userData.parts=asset.parts;return registerApprovedRoot(asset.group,name,label,pos,scale,asset.hit)}
function mountApprovedPaperCover(){const asset=createPaperCoverModels();registerApprovedRoot(asset.papers,'paperSheets','不透光黑纸（两片重叠）',[2.72,.04,1.08],1.08,asset.paperHit);registerApprovedRoot(asset.clip,'paperclip','回形针（单个）',[4.05,.04,1.10],1.08,asset.clipHit);asset.papers.userData.cue=asset.paperCue;asset.clip.userData.cue=asset.clipCue;asset.clip.rotation.x=-Math.PI/2;const h=homes.get(asset.clip);h.rotation.copy(asset.clip.rotation);return asset}
function torus(r,t,mat,parent,y=0){const m=new THREE.Mesh(new THREE.TorusGeometry(r,t,12,64),mat);m.rotation.x=Math.PI/2;m.position.y=y;parent.add(m);return m}
function cylinder(r1,r2,h,mat,parent,y=0){const m=new THREE.Mesh(new THREE.CylinderGeometry(r1,r2,h,48),mat);m.position.y=y;parent.add(m);return m}
function tube(points,r,mat,parent){const holder=new THREE.Group();for(let i=0;i<points.length-1;i++){const a=points[i],b=points[i+1],delta=b.clone().sub(a),m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,delta.length(),10),mat);m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),delta.normalize());holder.add(m)}parent.add(holder);return holder}

function beaker(name,label,pos,r,h,scale=1){const g=root(name,label,pos,scale);const body=new THREE.Mesh(new THREE.CylinderGeometry(r,r*.94,h,64,1,true),glass);body.position.y=h/2;g.add(body);cylinder(r*.94,r*.91,.035,glassEdge,g,.018);torus(r,.018,glassEdge,g,h);const sp=new THREE.Mesh(new THREE.ConeGeometry(.055,.12,20),glassEdge);sp.rotation.z=-Math.PI/2;sp.position.set(r+.025,h-.015,0);g.add(sp);return finish(g,new THREE.Mesh(new THREE.CylinderGeometry(r*1.18,r*1.18,h*1.18,24)))}
function tripod(){const g=root('tripod','三脚架',[-4.8,.01,.25],.92);torus(.48,.045,darkMetal,g,.88);for(let i=0;i<3;i++){const a=i/3*Math.PI*2,p0=new THREE.Vector3(Math.cos(a)*.38,.86,Math.sin(a)*.38),p1=new THREE.Vector3(Math.cos(a)*.58,.02,Math.sin(a)*.58);tube([p0,p1],.035,darkMetal,g)}return finish(g,new THREE.Mesh(new THREE.CylinderGeometry(.65,.7,1.05,20)))}
function gauze(){const g=root('gauze','石棉网',[-4.8,.91,.25],.92);const wire=new THREE.MeshStandardMaterial({color:0x8b8e88,roughness:.7,metalness:.55});for(let i=-8;i<=8;i++){const z=i*.06;const a=new THREE.Mesh(new THREE.BoxGeometry(1.08,.009,.012),wire);a.position.z=z;g.add(a);const b=new THREE.Mesh(new THREE.BoxGeometry(.012,.009,1.08),wire);b.position.x=z;g.add(b)}cylinder(.29,.29,.018,new THREE.MeshStandardMaterial({color:0xd6d0bb,roughness:.9}),g,.018);return finish(g,new THREE.Mesh(new THREE.BoxGeometry(1.25,.15,1.25)))}
function lamp(){const g=root('lamp','酒精灯',[-3.75,.01,.20],.8);const bowl=new THREE.Mesh(new THREE.SphereGeometry(.38,48,24),glass);bowl.scale.y=.68;bowl.position.y=.28;g.add(bowl);cylinder(.13,.17,.28,glassEdge,g,.54);torus(.14,.018,glassEdge,g,.68);const wick=new THREE.Mesh(new THREE.CylinderGeometry(.022,.022,.35,16),new THREE.MeshStandardMaterial({color:0xe9ddbd,roughness:1}));wick.position.y=.55;g.add(wick);const cap=new THREE.Group();cylinder(.13,.15,.24,glassEdge,cap,.12);const dome=new THREE.Mesh(new THREE.SphereGeometry(.13,32,16,0,Math.PI*2,0,Math.PI/2),glassEdge);dome.position.y=.24;cap.add(dome);cap.position.set(-.48,0,0);g.add(cap);g.userData.cap=cap;return finish(g,new THREE.Mesh(new THREE.BoxGeometry(1.15,.9,.85)))}
function dish(){const g=root('dish','培养皿',[-2.72,.02,.48],.72);cylinder(.43,.43,.055,glass,g,.03);torus(.44,.018,glassEdge,g,.06);const lid=new THREE.Group();cylinder(.47,.47,.065,glass,lid,.04);torus(.47,.018,glassEdge,lid,.075);lid.position.set(.48,.025,.04);g.add(lid);return finish(g,new THREE.Mesh(new THREE.BoxGeometry(1.45,.25,.9)))}
function bottle(name,label,pos,color=0xbfefff,iodine=false){const g=root(name,label,pos,.78),liquid=new THREE.MeshPhysicalMaterial({color,transparent:true,opacity:.62,roughness:.15,transmission:.28});cylinder(.25,.25,.72,glass,g,.36);cylinder(.18,.25,.18,glass,g,.79);cylinder(.21,.21,.10,iodine?darkMetal:new THREE.MeshStandardMaterial({color:0xe8ece7,roughness:.55}),g,.94);cylinder(.215,.215,.42,liquid,g,.24);if(iodine){const bulb=new THREE.Mesh(new THREE.SphereGeometry(.10,24,14),new THREE.MeshStandardMaterial({color:0x913025,roughness:.85}));bulb.scale.y=1.25;bulb.position.y=1.12;g.add(bulb);const pip=new THREE.Mesh(new THREE.CylinderGeometry(.015,.006,.46,16),glassEdge);pip.position.y=.78;g.add(pip)}return finish(g,new THREE.Mesh(new THREE.CylinderGeometry(.35,.35,1.35,20)))}
function washBottle(){const g=bottle('wash','洗瓶（清水）',[1.05,.02,.2],0xaeeaff);tube([new THREE.Vector3(0,.94,0),new THREE.Vector3(.12,1.22,0),new THREE.Vector3(.48,1.17,0),new THREE.Vector3(.62,1.08,0)],.025,new THREE.MeshStandardMaterial({color:0xe7efeb,roughness:.42}),g);return g}
function tweezers(){const g=root('tweezers','镊子',[-.25,.04,.75],.74);for(const z of [-.055,.055]){const pts=[new THREE.Vector3(-.55,.04,z),new THREE.Vector3(-.18,.055,z),new THREE.Vector3(.38,.025,z*.5),new THREE.Vector3(.62,0,0)];tube(pts,.025,metal,g)}tube([new THREE.Vector3(-.55,.04,-.055),new THREE.Vector3(-.66,.06,0),new THREE.Vector3(-.55,.04,.055)],.028,metal,g);g.rotation.y=-.18;return finish(g,new THREE.Mesh(new THREE.BoxGeometry(1.5,.22,.35)))}
function matchbox(){const g=root('matches','火柴盒与火柴',[.85,.03,.72],.66);const sleeve=new THREE.MeshStandardMaterial({color:0xb94a30,roughness:.85}),card=new THREE.MeshStandardMaterial({color:0xead5aa,roughness:.9});const outer=new THREE.Mesh(new THREE.BoxGeometry(.72,.22,.48),sleeve);outer.position.y=.13;g.add(outer);const tray=new THREE.Mesh(new THREE.BoxGeometry(.62,.16,.39),card);tray.position.set(.22,.14,0);g.add(tray);for(let i=0;i<7;i++){const s=new THREE.Mesh(new THREE.CylinderGeometry(.009,.009,.38,10),new THREE.MeshStandardMaterial({color:0xc99355,roughness:.9}));s.rotation.z=Math.PI/2;s.position.set(.2,.24,-.13+i*.043);g.add(s)}return finish(g,new THREE.Mesh(new THREE.BoxGeometry(1.15,.42,.72)))}
mountApprovedGeranium();
mountApprovedEquipment(createTripod(),'tripod','三脚架',[-5.55,.01,.10],1.38);
mountApprovedEquipment(createWireGauze(),'gauze','石棉网',[-5.55,1.19,.10],1.48);
mountApprovedEquipment(createAlcoholLamp(),'lamp','酒精灯（含可盖合灯帽）',[-4.15,.01,1.18],1.20);
mountApprovedEquipment(createLargeBeaker(),'largeBeaker','大烧杯',[-3.15,.01,.12],1.00);
mountApprovedEquipment(createSmallBeaker(),'smallBeaker','小烧杯',[-1.72,.01,.18],1.00);
mountApprovedEquipment(createPetriDish(),'dish','培养皿（含皿盖）',[-2.55,.02,1.26],1.00);
mountApprovedEquipment(createWashBottle(),'wash','洗瓶（清水）',[1.62,.02,.15],1.10);
mountApprovedEquipment(createAlcoholBottle(),'alcohol','酒精瓶',[2.72,.02,.17],1.10);
mountApprovedEquipment(createIodineBottle(),'iodine','碘液瓶（含滴管）',[3.78,.02,.20],1.08);
mountApprovedEquipment(createTweezers(),'tweezers','直形尖头镊子',[.62,.04,1.14],.95);
mountApprovedEquipment(createMatchbox(),'matches','火柴盒与可取火柴',[-.35,.03,.18],1.10);
mountApprovedPaperCover();
const boosts={plant:1.36,tripod:1.30,gauze:1.30,lamp:1.24,largeBeaker:1.30,smallBeaker:1.25,dish:1.18,wash:1.18,alcohol:1.16,iodine:1.16,tweezers:1.12,matches:1.18,paperSheets:1,paperclip:1};
for(const o of roots){o.scale.multiplyScalar(boosts[o.name]||1);if(o.name==='plant')o.position.x=5.05;const h=homes.get(o);h.position.copy(o.position);h.scale.copy(o.scale)}

const floor=new THREE.Mesh(new THREE.PlaneGeometry(14,4.8),new THREE.ShadowMaterial({color:0x000000,opacity:.20}));floor.rotation.x=-Math.PI/2;floor.position.set(0,-1.59,.35);floor.receiveShadow=true;scene.add(floor);
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),dragPlane=new THREE.Plane(),point=new THREE.Vector3(),offset=new THREE.Vector3(),viewNormal=new THREE.Vector3();
function pointerRay(e){const r=renderer.domElement.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;raycaster.setFromCamera(pointer,camera)}
const screenVector=new THREE.Vector3();
renderer.domElement.addEventListener('pointercancel',()=>{drag=null;renderer.domElement.style.cursor='default'});
function screenPosition(object){object.getWorldPosition(screenVector);screenVector.project(camera);return{x:(screenVector.x*.5+.5)*W,y:(-screenVector.y*.5+.5)*H}}
function nearExperimentLeaf(object,radius){const leaf=roots.find(o=>o.name==='plant').userData.experimentLeaf,a=screenPosition(object),b=screenPosition(leaf);return Math.hypot(a.x-b.x,a.y-b.y)<radius}
function setToolCue(name){for(const o of roots){if(o.userData.cue)o.userData.cue.visible=o.name===name}}
function attachPapers(){const plant=roots.find(o=>o.name==='plant'),leaf=plant.userData.experimentLeaf,papers=roots.find(o=>o.name==='paperSheets');papers.userData.cue.visible=false;leaf.add(papers);papers.position.set(-.025,0,0);papers.rotation.set(0,0,0);papers.scale.setScalar(.30);papers.userData.attached=true;papers.children.find(o=>o.userData.root===papers).visible=false;step='clip';setToolCue('paperclip');guide('用回形针固定','青色光圈标出当前可拖动的回形针；拖到叶片圆圈附近即可自动夹住左侧叶缘');toast('黑纸已吸附，现在拖动发光的回形针')}
function attachClip(){const plant=roots.find(o=>o.name==='plant'),leaf=plant.userData.experimentLeaf,clip=roots.find(o=>o.name==='paperclip');clip.userData.cue.visible=false;leaf.add(clip);clip.position.set(-.09,.035,0);clip.rotation.set(-Math.PI/2,0,0);clip.scale.setScalar(.30);clip.userData.attached=true;clip.children.find(o=>o.userData.root===clip).visible=false;plant.userData.selectionRing.visible=false;step='lightReady';setToolCue('');const action=document.querySelector('#lightAction'),button=document.querySelector('#lightBtn');action.style.display='block';action.classList.remove('complete');button.disabled=false;button.textContent='开始照光 10S';guide('遮光处理完成','黑纸与回形针已经固定，请点击“开始照光 10S”');toast('固定完成：现在可以开始10秒光照处理')}
renderer.domElement.addEventListener('pointerdown',e=>{if(!experimentMode||paused)return;pointerRay(e);const hit=raycaster.intersectObjects(pickables,false).find(h=>{const n=h.object.userData.root.name;return(n!=='paperSheets'||step==='paper')&&(n!=='paperclip'||step==='clip')&&(n!=='plant'||step!=='lighting')});if(!hit)return;const object=hit.object.userData.root;camera.getWorldDirection(viewNormal);dragPlane.setFromNormalAndCoplanarPoint(viewNormal,object.position);raycaster.ray.intersectPlane(dragPlane,point);offset.copy(object.position).sub(point);drag={id:e.pointerId,object};renderer.domElement.setPointerCapture(e.pointerId);renderer.domElement.style.cursor='grabbing'});
renderer.domElement.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;pointerRay(e);if(raycaster.ray.intersectPlane(dragPlane,point)){drag.object.position.copy(point).add(offset);drag.object.position.x=THREE.MathUtils.clamp(drag.object.position.x,-6.3,6.1);drag.object.position.y=THREE.MathUtils.clamp(drag.object.position.y,-1.7,2.4)}});
renderer.domElement.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const o=drag.object;drag=null;renderer.domElement.style.cursor='default';const v=o.position.clone().project(camera),px=(v.x*.5+.5)*W,py=(-v.y*.5+.5)*H;if(o.name==='plant'&&step==='dark'&&px>735&&px<1120&&py>125&&py<555){o.visible=true;if(!o.userData.inCabinet)o.position.y+=.28;o.userData.inCabinet=true;o.position.z=-1.15;o.scale.copy(homes.get(o).scale).multiplyScalar(.56);document.querySelector('#cabinetZone').style.display='none';document.querySelector('#cabinetDoor').classList.add('ready');toast('天竺葵已放入暗处理柜，在柜内可以看到植株');guide('关闭柜门','点击唯一的柜门开始 10 秒暗处理');return}if(o.name==='plant'&&o.userData.inCabinet){o.userData.inCabinet=false;o.scale.copy(homes.get(o).scale);if(darkComplete&&px>980&&py<700){step='paper';document.querySelector('#sunZone').style.display='none';o.userData.selectionRing.visible=true;setToolCue('paperSheets');guide('第二步：局部遮光','青色光圈标出当前可拖动的两片黑纸；拖到叶片圆圈附近即可自动吸附');toast('已到达阳光区，请拖动发光的黑纸')}else{step='retrieve';guide('把天竺葵移到阳光区','请拖入右侧黄色虚线区域，区域内任意位置都能触发');toast('还未进入阳光区，请拖到黄色虚线框内')}return}if(o.name==='plant'&&darkComplete&&step==='retrieve'&&px>980&&py<700){step='paper';document.querySelector('#sunZone').style.display='none';o.userData.selectionRing.visible=true;setToolCue('paperSheets');guide('第二步：局部遮光','青色光圈标出当前可拖动的两片黑纸；拖到叶片圆圈附近即可自动吸附');toast('已到达阳光区，请拖动发光的黑纸');return}if(o.name==='paperSheets'){if(step==='paper'&&nearExperimentLeaf(o,280))attachPapers();else{restore(o);o.userData.cue.visible=true;toast('再靠近一点即可：把发光黑纸拖进叶片圆圈')}return}if(o.name==='paperclip'){if(step==='clip'&&nearExperimentLeaf(o,240))attachClip();else{restore(o);o.userData.cue.visible=true;toast('把发光回形针拖进叶片圆圈，会自动固定左侧')}return}toast(`${o.userData.label}已放置，可继续调整`)});
renderer.domElement.addEventListener('dblclick',e=>{pointerRay(e);const hit=raycaster.intersectObjects(pickables,false)[0];if(!hit)return;restore(hit.object.userData.root);toast(`${hit.object.userData.root.userData.label}已归位`)});
renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();const s=THREE.MathUtils.clamp(camera.zoom-e.deltaY*.0007,.82,1.45);camera.zoom=s;camera.updateProjectionMatrix()},{passive:false});

function restore(o){const h=homes.get(o);if(o.parent!==scene)scene.add(o);o.position.copy(h.position);o.rotation.copy(h.rotation);o.scale.copy(h.scale);o.visible=true;o.userData.inCabinet=false;o.userData.attached=false;if(o.userData.cue)o.userData.cue.visible=false;const hit=o.children.find(c=>c.userData.root===o);if(hit)hit.visible=true}
function guide(title,text){document.querySelector('#guideTitle').textContent=title;document.querySelector('#guideText').textContent=text}
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2100)}
function setMode(on){if(!on&&(darkTimer||lightTimer))return toast('处理正在计时，请等待完成或使用重置实验');experimentMode=on;document.querySelector('#prepareMode').classList.toggle('active',!on);document.querySelector('#experimentMode').classList.toggle('active',on);document.querySelector('#labels').style.display=on?'none':'block';document.querySelector('#cabinetZone').style.display=on&&step==='dark'?'block':'none';document.querySelector('#sunZone').style.display=on&&step==='retrieve'?'block':'none';document.querySelector('#lightAction').style.display=on&&(step==='lightReady'||step==='lightComplete')?'block':'none';document.querySelector('#pauseBtn').disabled=!on;guide(on?'第一步：暗处理':'准备实验',on?'拖动天竺葵进入暗处理柜，然后点击柜门':'查看器材名称与位置，确认后点击“开始实验”');toast(on?'实验模式：按住器材即可拖动':'准备模式：已显示器材标签')}
document.querySelector('#prepareMode').onclick=()=>setMode(false);document.querySelector('#experimentMode').onclick=()=>setMode(true);
document.querySelector('#pauseBtn').onclick=()=>{paused=!paused;document.querySelector('#pauseBtn').textContent=paused?'继续':'暂停';toast(paused?'实验已暂停':'实验已继续')};
document.querySelector('#resetBtn').addEventListener('click',()=>{paused=false;document.querySelector('#pauseBtn').textContent='暂停'});
document.querySelector('#resetBtn').onclick=()=>{clearInterval(darkTimer);clearInterval(lightTimer);darkTimer=lightTimer=null;darkSeconds=10;darkComplete=false;lightElapsed=0;lightComplete=false;step='dark';roots.forEach(restore);roots.find(o=>o.name==='plant').userData.selectionRing.visible=false;document.querySelector('#cabinetDoor').classList.remove('closed','ready');document.querySelector('#timer').style.display='none';document.querySelector('#sunZone').style.display='none';const glow=document.querySelector('#sunGlow'),action=document.querySelector('#lightAction'),button=document.querySelector('#lightBtn');glow.classList.remove('lighting');glow.style.setProperty('--light-progress','0');action.style.display='none';action.classList.remove('complete');action.querySelector('span').textContent='黑纸和回形针固定完成后开始';button.disabled=false;button.textContent='开始照光 10S';camera.zoom=1;camera.updateProjectionMatrix();setMode(false);rebuildLabels();toast('实验已重置')};
document.querySelector('#fullBtn').onclick=async()=>{try{if(!document.fullscreenElement){await document.documentElement.requestFullscreen();if(screen.orientation?.lock)await screen.orientation.lock('landscape').catch(()=>{})}else await document.exitFullscreen()}catch{toast('当前设备不支持自动全屏，请使用浏览器全屏')}};
document.querySelector('#lightBtn').onclick=()=>{if(!experimentMode)return toast('请先进入实验模式');if(step!=='lightReady'||lightTimer)return toast(lightComplete?'光照处理已经完成':'请先用回形针固定黑纸');step='lighting';lightElapsed=0;const action=document.querySelector('#lightAction'),timer=document.querySelector('#timer'),glow=document.querySelector('#sunGlow');action.style.display='none';timer.style.display='grid';document.querySelector('#timerValue').textContent='10';glow.classList.add('lighting');glow.style.setProperty('--light-progress','0');guide('光照处理进行中','保持黑纸固定，阳光强度正在逐渐增强，教学时间压缩为10秒');toast('已开始照光，黑纸和回形针保持固定');lightTimer=setInterval(()=>{if(paused)return;lightElapsed=Math.min(10,lightElapsed+.1);const progress=lightElapsed/10,remaining=Math.max(0,Math.ceil(10-lightElapsed));glow.style.setProperty('--light-progress',progress.toFixed(3));document.querySelector('#timerValue').textContent=remaining;if(lightElapsed>=10){clearInterval(lightTimer);lightTimer=null;lightComplete=true;step='lightComplete';timer.style.display='none';glow.classList.remove('lighting');glow.style.setProperty('--light-progress','1');const button=document.querySelector('#lightBtn');action.style.display='block';action.classList.add('complete');button.disabled=true;button.textContent='光照处理完成';action.querySelector('span').textContent='当前状态已保留，等待确认下一步';guide('10秒光照处理完成','黑纸遮光状态与叶片位置已保留，请确认后再进入下一步');toast('光照处理完成')}} ,100)};
document.querySelector('#cabinetDoor').onclick=()=>{if(!experimentMode)return toast('请先点击“开始实验”');const plant=roots.find(o=>o.name==='plant'),door=document.querySelector('#cabinetDoor');if(!plant.userData.inCabinet)return toast('请先把天竺葵拖入柜内');if(darkTimer)return;door.classList.add('closed');darkSeconds=10;const timer=document.querySelector('#timer');timer.style.display='grid';document.querySelector('#timerValue').textContent=darkSeconds;guide('暗处理进行中','柜门已关闭，教学时间压缩为 10 秒');darkTimer=setInterval(()=>{if(paused)return;darkSeconds--;document.querySelector('#timerValue').textContent=darkSeconds;if(darkSeconds<=0){clearInterval(darkTimer);darkTimer=null;darkComplete=true;step='retrieve';timer.style.display='none';door.classList.remove('closed','ready');document.querySelector('#sunZone').style.display='block';guide('暗处理完成','黄色虚线框就是阳光区，把柜内天竺葵拖入框内任意位置');toast('柜门已让出拖拽区域，可以直接按住柜内植株')}} ,1000)};

function rebuildLabels(){camera.updateMatrixWorld(true);const host=document.querySelector('#labels');host.innerHTML='';for(const o of roots){const bounds=new THREE.Box3().setFromObject(o),v=bounds.getCenter(new THREE.Vector3());v.y=bounds.max.y+.10;v.project(camera);const el=document.createElement('span');el.className='label';el.textContent=o.userData.label;el.style.left=`${(v.x*.5+.5)*W}px`;el.style.top=`${(-v.y*.5+.5)*H}px`;host.append(el)}}
setupLeafTransfer({roots,scene,camera,canvas:renderer.domElement,restore,guide,toast,isActive:()=>experimentMode&&!paused});
setupLeafRinse({roots,scene,camera,canvas:renderer.domElement,restore,guide,toast,isActive:()=>experimentMode&&!paused});
setupWaterBath({roots,scene,camera,canvas:renderer.domElement,restore,guide,toast,isActive:()=>experimentMode&&!paused});
setupLeafStain({roots,scene,camera,canvas:renderer.domElement,restore,guide,toast,isActive:()=>experimentMode&&!paused});
setupPhenomenonCloseup({leaf:roots.find(o=>o.name==='plant').userData.experimentLeaf,stage});
setupSceneNavigation({stage,canvas:renderer.domElement,isObjectAt:e=>{pointerRay(e);return raycaster.intersectObjects(roots,true).some(h=>{if(h.object.type!=='Mesh')return false;for(let o=h.object;o;o=o.parent)if(!o.visible)return false;return h.object.material?.opacity!==0})}});
function resize(){const s=Math.min(innerWidth/W,innerHeight/H);stage.style.transform=`scale(${s})`;stage.style.left=`${(innerWidth-W*s)/2}px`;stage.style.top=`${(innerHeight-H*s)/2}px`;stage.style.position='fixed'}addEventListener('resize',resize);resize();rebuildLabels();
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const t=clock.getElapsedTime(),plant=roots.find(o=>o.name==='plant');if(plant.visible&&!plant.userData.inCabinet)plant.rotation.y=Math.sin(t*.35)*.012;const ring=plant.userData.selectionRing;if(ring)ring.material.opacity=.55+.3*Math.sin(t*2.4);for(const o of roots){if(o.userData.cue&&o.userData.cue.visible){o.userData.cue.material.opacity=.48+.28*Math.sin(t*4.2);const s=1+.08*Math.sin(t*4.2);o.userData.cue.scale.setScalar(s)}}renderer.render(scene,camera)}animate();
