import * as THREE from './vendor/three.module.js';

export function setupWaterBath({roots,scene,camera,canvas,restore,guide,toast,isActive}){
 const get=n=>roots.find(o=>o.name===n),small=get('smallBeaker'),large=get('largeBeaker'),lamp=get('lamp'),alcohol=get('alcohol'),wash=get('wash'),matches=get('matches'),gauze=get('gauze'),tripod=get('tripod'),leaf=get('plant').userData.experimentLeaf;
 const S=small.userData.parts,L=large.userData.parts,F=lamp.userData.parts,M=matches.userData.parts;
 let phase=-1,selected=false,down=null,job=null,elapsed=0,last=performance.now(),lit=false;
 const panel=document.createElement('div');panel.id='bathAction';panel.style.cssText='display:none;position:absolute;left:750px;bottom:62px;z-index:15;padding:12px;max-width:540px;background:#09273cee;border:1px solid #8be4d0;border-radius:12px';
 const button=document.createElement('button'),hint=document.createElement('div');hint.style.cssText='font-size:16px;color:#def6ee;margin-top:8px';panel.append(button,hint);document.querySelector('#stage').append(panel);
 const steps=[['打开酒精瓶，选择倒入','点击小烧杯，或拖动酒精瓶靠近小烧杯',alcohol,small],['选择洗瓶加水','点击大烧杯，或拖动洗瓶靠近大烧杯',wash,large],['选择小烧杯','点击大烧杯，将小烧杯放入水中',small,large],['选择水浴烧杯组','点击石棉网，将烧杯组放上三脚架',large,gauze],['将酒精灯移至架下','点击三脚架，或把酒精灯拖到架下',lamp,tripod],['取下酒精灯帽','打开灯帽后才能点火',lamp,lamp],['拉开火柴盒，取出火柴','取出后用火柴头在盒侧磷片上划擦',matches,matches],['划擦火柴','拖动露出的火柴，让火柴头沿盒侧摩擦片划过',matches,matches],['用火柴点燃酒精灯','点击酒精灯，或把火柴拖近灯芯',matches,lamp],['水浴加热中','教学时间15秒；完成后请盖帽熄灭',null,null],['盖帽熄灭酒精灯','叶片已褪色，酒精变绿',lamp,lamp]];
 function show(n){phase=n;selected=false;panel.style.display='block';button.disabled=n===9;button.textContent=n===7?'辅助划擦点燃':steps[n][0];hint.textContent=n===7?'按住火柴或盒侧，左右划动一小段；也可点击按钮辅助划擦':steps[n][1];guide(steps[n][0],hint.textContent);document.querySelector('#lightAction').style.display='none';document.querySelector('#leafAction').style.display='none'}
 function screen(o){const p=o.getWorldPosition(new THREE.Vector3()).project(camera),r=canvas.getBoundingClientRect();return new THREE.Vector2(r.left+(p.x+1)*r.width/2,r.top+(1-p.y)*r.height/2)}
 function near(e,o,r=110){return screen(o).distanceTo(new THREE.Vector2(e.clientX,e.clientY))<r*canvas.getBoundingClientRect().width/1672}
 function tween(duration,update,done){job={time:0,duration,update,done};button.disabled=true}
 const stream=new THREE.Group(),waterMat=new THREE.MeshPhysicalMaterial({color:0xd2efff,transparent:true,opacity:.7,roughness:.08,transmission:.7,depthWrite:false});scene.add(stream);stream.visible=false;const segments=Array.from({length:24},()=>{const m=new THREE.Mesh(new THREE.CylinderGeometry(1,1,1,8),waterMat);stream.add(m);return m});
 function jet(a,b,t){stream.visible=true;const curve=new THREE.QuadraticBezierCurve3(a,a.clone().lerp(b,.4).add(new THREE.Vector3(.10,.06,0)),b);segments.forEach((m,i)=>{const p=curve.getPoint(i/24),q=curve.getPoint((i+1)/24),d=q.clone().sub(p);m.position.copy(p).add(q).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.clone().normalize());const r=.012*(1-i/48)*(1+.1*Math.sin(t*32+i));m.scale.set(r,d.length(),r)})}
 function fill(source,target,liquid,top,water){const start=source.position.clone(),rot=source.quaternion.clone(),end=target.getWorldPosition(new THREE.Vector3()).add(new THREE.Vector3(-.42,1.12,.02));if(!water)source.userData.parts.cap.position.copy(source.userData.parts.capOpen);liquid.visible=top.visible=true;
 tween(2.5,(t)=>{source.position.copy(start).lerp(end,Math.min(t*4,1));source.rotation.z=water?-.12:-1.15*Math.min(t*4,1);source.updateWorldMatrix(true,true);const local=water?new THREE.Vector3(.495,.592,0):new THREE.Vector3(0,.60,0);const a=source.localToWorld(local),b=target.localToWorld(new THREE.Vector3(0,water?.377:.329,0));const q=THREE.MathUtils.smoothstep(t,.2,.9);liquid.scale.y=Math.max(.01,q);liquid.position.y=(water?.035:.027)+(water?.17:.15)*q;top.position.y=(water?.035:.027)+(water?.34:.30)*q;if(t>.2&&t<.92)jet(a,b,t);else stream.visible=false},()=>{stream.visible=false;source.quaternion.copy(rot);restore(source);if(!water)source.userData.parts.cap.position.copy(source.userData.parts.capClosed);show(phase+1)})}
 function place(child,parent,pos,next){parent.attach(child);const start=child.position.clone(),r0=child.quaternion.clone();child.userData.bathMounted=true;tween(.65,t=>{const q=t*t*(3-2*t);child.position.copy(start).lerp(pos,q);child.quaternion.copy(r0).slerp(new THREE.Quaternion(),q)},()=>{if(next===5)F.cap.position.copy(F.capClosed.position);show(next)})}
 const bubbles=new THREE.Group();large.add(bubbles);bubbles.visible=false;for(let i=0;i<30;i++){const b=new THREE.Mesh(new THREE.SphereGeometry(.006+(i%3)*.002,8,6),new THREE.MeshPhysicalMaterial({color:0xf0fdff,transparent:true,opacity:.42,roughness:.06}));b.userData.seed=i/30;bubbles.add(b)}
 const materials=[];leaf.traverse(o=>{if(o.isMesh&&o.name!==''){const list=Array.isArray(o.material)?o.material:[o.material];for(const m of list)if(m.color&&!materials.some(v=>v.m===m))materials.push({m,color:m.color.clone(),map:m.map})}});
 // A uniform extracts chlorophyll without replacing the leaf mesh, UVs or shadeRecord.
 const bleach={value:0};leaf.traverse(o=>{if(!o.isMesh||o===get('plant').userData.selectionRing)return;const list=Array.isArray(o.material)?o.material:[o.material];for(const mat of list){if(mat.userData.bathBleach)continue;mat.userData.bathBleach=true;mat.onBeforeCompile=shader=>{shader.uniforms.bathBleach=bleach;shader.fragmentShader='uniform float bathBleach;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>','#include <map_fragment>\nfloat leafLuma=dot(diffuseColor.rgb,vec3(0.299,0.587,0.114));\ndiffuseColor.rgb=mix(diffuseColor.rgb,vec3(0.87,0.83,0.59)*(0.72+leafLuma*0.28),bathBleach);')};mat.customProgramCacheKey=()=> 'leaf-bath-bleach-v1';mat.needsUpdate=true}});
 const liquidColor=S.liquid.material.color.clone();
 function ignite(){lit=true;F.flame.visible=true;restore(matches);M.activeMatch.visible=false;M.flame.visible=false;show(9);elapsed=0;bubbles.visible=true;document.querySelector('#timer').style.display='grid';document.querySelector('#timerValue').textContent='15'}
 function perform(){if(!isActive()||job)return;
 if(phase===0)fill(alcohol,small,S.liquid,S.liquidTop,false);
 else if(phase===1)fill(wash,large,L.water,L.waterTop,true);
 else if(phase===2)place(small,large,new THREE.Vector3(0,.04,0),3);
 else if(phase===3)place(large,gauze,new THREE.Vector3(0,.035,0),4);
 else if(phase===4)place(lamp,tripod,new THREE.Vector3(0,0,0),5);
 else if(phase===5){F.cap.position.copy(F.capRest.position);show(6)}
 else if(phase===6){M.tray.position.x=.38;M.activeMatch.visible=true;M.activeMatch.position.set(.38,.25,.30);show(7)}
 else if(phase===8)ignite();
 else if(phase===10){const from=F.cap.position.clone();tween(.7,t=>F.cap.position.copy(from).lerp(F.capClosed.position,t),()=>{lit=false;F.flame.visible=false;phase=11;button.disabled=true;button.textContent='水浴加热完成';hint.textContent='灯已熄灭，等待确认漂洗步骤';guide('水浴加热完成','叶片已逐渐褪为黄白色，酒精变绿；原遮光范围仍保留');leaf.userData.heatingComplete=true})}
 }
 function lightMatch(){M.flame.visible=true;show(8);hint.textContent='拖动燃烧的火柴靠近灯芯即可点火，也可点击酒精灯';toast('火柴已划燃，可以拖动到灯芯');selected=true}
 function snapMatch(headX){M.activeMatch.rotation.set(0,0,0);M.activeMatch.position.set(headX-.17,.18,.255);M.activeMatch.updateWorldMatrix(true,true)}
 function strikeAssist(){const start=M.activeMatch.position.clone();hint.textContent='火柴头贴住磷片，正在划擦';tween(.85,t=>{if(t<.35)M.activeMatch.position.copy(start).lerp(new THREE.Vector3(.07,.18,.255),t/.35);else snapMatch(.24-.46*(t-.35)/.65)},lightMatch)}
 button.onclick=()=>{if(!isActive()||job)return;if([5,6,10].includes(phase)){perform();return}if(phase===7){strikeAssist();return}selected=true;button.textContent='已选中，请点击目标器材';toast(steps[phase][1])};
 let matchDrag=null;const ray=new THREE.Raycaster();function rayAt(e){const r=canvas.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera)}
 // Burning match remains its own draggable object, not the matchbox root.
 let burningDrag=null;
 canvas.addEventListener('pointerdown',e=>{if(phase!==8||job||!isActive()||!near(e,M.activeMatch,100))return;e.stopImmediatePropagation();const world=M.activeMatch.getWorldPosition(new THREE.Vector3());rayAt(e);const plane=new THREE.Plane().setFromNormalAndCoplanarPoint(camera.getWorldDirection(new THREE.Vector3()),world),hit=ray.ray.intersectPlane(plane,new THREE.Vector3());if(!hit)return;burningDrag={id:e.pointerId,plane,offset:world.clone().sub(hit)};canvas.setPointerCapture(e.pointerId)},true);
 canvas.addEventListener('pointermove',e=>{if(!burningDrag)return;e.stopImmediatePropagation();if(!isActive())return;rayAt(e);const p=ray.ray.intersectPlane(burningDrag.plane,new THREE.Vector3());if(p)M.activeMatch.position.copy(matches.worldToLocal(p.add(burningDrag.offset)))},true);
 canvas.addEventListener('pointerup',e=>{if(!burningDrag)return;e.stopImmediatePropagation();burningDrag=null;if(isActive()&&near(e,lamp,150))ignite()},true);
 canvas.addEventListener('pointercancel',()=>burningDrag=null,true);
 canvas.addEventListener('pointerdown',e=>{if(phase<0||phase>10||!isActive()||job)return;if(phase===7&&(near(e,M.activeMatch,125)||near(e,M.striker,100))){e.stopImmediatePropagation();snapMatch(.22);const r=canvas.getBoundingClientRect(),a=matches.localToWorld(new THREE.Vector3(-.275,.18,.255)).project(camera),b=matches.localToWorld(new THREE.Vector3(.275,.18,.255)).project(camera),axis=new THREE.Vector2((b.x-a.x)*r.width/2,-(b.y-a.y)*r.height/2);const length=Math.max(axis.length(),1);axis.normalize();matchDrag={axis,length,start:new THREE.Vector2(e.clientX,e.clientY),max:0};hint.textContent='已贴住摩擦片，沿盒侧向任一方向划动即可';canvas.setPointerCapture(e.pointerId);return}const s=steps[phase];if(!s[2])return;if(selected&&near(e,s[3])){e.stopImmediatePropagation();perform();return}if(near(e,s[2])){selected=true;down={x:e.clientX,y:e.clientY};hint.textContent='已选中：'+s[1]}},true);
 canvas.addEventListener('pointermove',e=>{if(!matchDrag)return;e.stopImmediatePropagation();if(!isActive()){matchDrag.start.set(e.clientX,e.clientY);return}const distance=Math.abs(new THREE.Vector2(e.clientX,e.clientY).sub(matchDrag.start).dot(matchDrag.axis)),threshold=Math.max(12,Math.min(28,matchDrag.length*.28));matchDrag.max=Math.max(matchDrag.max,distance);snapMatch(.22-.44*Math.min(distance/threshold,1));hint.textContent='划擦进度 '+Math.min(100,Math.round(distance/threshold*100))+'%';if(distance>=threshold){matchDrag=null;lightMatch()}},true);
 canvas.addEventListener('pointercancel',()=>{matchDrag=null;down=null},true);
 canvas.addEventListener('pointerup',e=>{if(matchDrag){e.stopImmediatePropagation();matchDrag=null;return}if(!down)return;down=null;if(isActive()&&!job&&phase>=0&&phase<9&&phase!==7&&near(e,steps[phase][3]))queueMicrotask(perform)},true);
 const reset=()=>{phase=-1;job=null;selected=false;matchDrag=null;down=null;lit=false;elapsed=0;bleach.value=0;roots.forEach(o=>o.userData.bathMounted=false);F.flame.visible=false;F.cap.position.copy(F.capRest.position);alcohol.userData.parts.cap.position.copy(alcohol.userData.parts.capClosed);M.activeMatch.visible=false;M.tray.position.x=0;M.flame.visible=false;bubbles.visible=stream.visible=false;S.liquid.visible=S.liquidTop.visible=L.water.visible=L.waterTop.visible=false;S.liquid.material.color.copy(liquidColor);panel.style.display='none';leaf.userData.heatingComplete=false};document.querySelector('#resetBtn').addEventListener('click',reset);
 // Attached equipment moves with its parent assembly; avoid the old world-plane
 // drag handler writing world coordinates into a nested object's local position.
 canvas.addEventListener('pointerdown',e=>{if(phase<0)return;if(job||phase===9){e.stopImmediatePropagation();return}if(!isActive())return;rayAt(e);const hits=ray.intersectObjects(roots.flatMap(o=>o.children.filter(c=>c.userData.root===o)),false);if(hits[0]?.object.userData.root.userData.bathMounted)e.stopImmediatePropagation()},true);
 canvas.addEventListener('dblclick',e=>{if(phase>=0)e.stopImmediatePropagation()},true);
 function tick(now){requestAnimationFrame(tick);const dt=Math.min((now-last)/1000,.05);last=now;if(phase<0&&leaf.userData.inBeaker)show(0);if(!isActive())return;if(job){job.time+=dt;job.update(Math.min(job.time/job.duration,1));if(job.time>=job.duration){const done=job.done;job=null;button.disabled=false;done()}}if(lit){F.flame.scale.set(1+.06*Math.sin(now*.019),1+.10*Math.sin(now*.023),1)}if(phase===9){elapsed=Math.min(15,elapsed+dt);const p=elapsed/15;bleach.value=THREE.MathUtils.smoothstep(p,.12,1);S.liquid.material.color.copy(liquidColor).lerp(new THREE.Color(0x4b8c39),bleach.value);bubbles.children.forEach((b,i)=>{const q=(elapsed*(.12+p*.22)+b.userData.seed)%1;b.visible=i<Math.floor(Math.max(0,p-.15)*36);const a=i*2.4;b.position.set(Math.cos(a)*.29,.045+q*.29,Math.sin(a)*.29);b.scale.setScalar(.5+p*.8)});document.querySelector('#timerValue').textContent=String(Math.ceil(15-elapsed));if(elapsed>=15){bubbles.visible=false;document.querySelector('#timer').style.display='none';show(10)}}}requestAnimationFrame(tick);
}
